- java/hello-world/src/main/java/software/amazon/awscdk/examples/HelloJavaApp.java
Deleted the following import statement from HelloJavaApp.java:
import java.util.Arrays
> Removed unused package import from Java example

- typescript/ecs/cluster/index.ts
Cluster was not using public subnets, so setting this field to true would throw error
> Remove associatePublicIp

- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/package.json
- typescript/resource-overrides/index.ts
This fixes the issue of cfn-resource#propertyOverrides being readonly (modifying only in constructor) but there appears to be an issue with adding a null value as an override, eg: bucketResource.addPropertyOverride('Foo', null);
This is just to unblock the build errors for the moment.
> Fix resource override

- README.md
- java/lambda-cron/README.md
- java/lambda-cron/cdk.json
- java/lambda-cron/pom.xml
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronApp.java
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
- java/lambda-cron/src/test/java/software/amazon/awscdk/examples/LambdaCronStackTest.java
- java/lambda-cron/src/test/java/software/amazon/awscdk/examples/TestUtils.java
- java/lambda-cron/src/test/resources/software/amazon/awscdk/examples/testCronLambdaExpected.json
No issue. I just thought the Java section looked a bit sad.
Creates a Java copy of the Lambda Cron example present in the Python and Typescript examples (using the same Python code as that seemed simplest).
> Add Java version of the Lambda Cron example

- typescript/api-cors-lambda-crud-dynamodb/index.ts
- typescript/application-load-balancer/index.ts
- typescript/appsync-graphql-dynamodb/index.ts
- typescript/classic-load-balancer/index.ts
- typescript/custom-resource/index.ts
- typescript/ecs/cluster/index.ts
- typescript/ecs/ecs-load-balanced-service/index.ts
- typescript/ecs/ecs-service-with-advanced-alb-config/index.ts
- typescript/ecs/ecs-service-with-logging/index.ts
- typescript/ecs/ecs-service-with-logging/package-lock.json
- typescript/ecs/ecs-service-with-task-networking/index.ts
- typescript/ecs/ecs-service-with-task-placement/index.ts
- typescript/ecs/fargate-load-balanced-service/index.ts
- typescript/ecs/fargate-service-with-auto-scaling/index.ts
- typescript/ecs/fargate-service-with-auto-scaling/package-lock.json
- typescript/ecs/fargate-service-with-local-image/index.ts
- typescript/ecs/fargate-service-with-local-image/local-image/app.py
- typescript/ecs/fargate-service-with-logging/index.ts
- typescript/ecs/fargate-service-with-logging/package-lock.json
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-environment/index.ts
- typescript/lambda-cron/index.ts
- typescript/my-widget-service/index.ts
- typescript/resource-overrides/index.ts
- typescript/static-site/index.ts
- typescript/static-site/package.json
- typescript/static-site/static-site.ts
- typescript/stepfunctions-job-poller/index.ts
*Issue #, if available:* #49
Updated typescript examples to account for breaking changes
- Replaced "app.run()" with "app.synth()"
- Replaced "node.getContext()" with "node.tryGetContext()"
- Replaced "route53.AliasRecord()" with "route53.ARecord()"
> Update for cdk0.34.0

- .gitignore
- python/application-load-balancer/app.py
- python/classic-load-balancer/app.py
- python/custom-resource/app.py
- python/custom-resource/custom-resource-handler.py
- python/custom-resource/my_custom_resource.py
- python/ecs/cluster/app.py
- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/ecs-service-with-advanced-alb-config/app.py
- python/ecs/ecs-service-with-task-placement/app.py
- python/ecs/fargate-load-balanced-service/app.py
- python/ecs/fargate-service-with-autoscaling/app.py
- python/lambda-cron/app.py
- python/stepfunctions/app.py
*Fixes #61 *
Updating to latest CDK version.  All Python examples have been ported but some of the ECS examples are broken due to https://github.com/aws/jsii/issues/537 which will hopefully be fixed in the next day or so.
> Updating Python examples to 0.36.1

- README.md
Quick change to the description of ecs-service-with-logging - it uses ECS, not Fargate.
Also changed "fronted" to "frontend" to match the description of fargate-service-with-logging below.
> ecs-service-with-logging - ECS, not Fargate

- typescript/ecs/cluster/index.ts
This example now works with the latest version of the cdk 0.37.0
> Remove comment from the ecs cluster example

- typescript/resource-overrides/README.md
- typescript/resource-overrides/index.ts
The README explains that the example does not end up in a deployable
state.
Also slighly edit example to use some of the nicer new features.
Fixes #68.
> chore(overrides): add README to "overrides" example

- python/ecs/cluster/app.py
- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/ecs-service-with-advanced-alb-config/app.py
- python/ecs/ecs-service-with-task-networking/app.py
- python/ecs/ecs-service-with-task-placement/app.py
- python/ecs/fargate-load-balanced-service/app.py
- python/ecs/fargate-service-with-autoscaling/app.py
> Updating all Python examples for CDK release 0.38

- typescript/ecs/fargate-service-with-local-image/local-image/app.py
flasks app.run was accidentally renamed to app.synth in global rename
> rename flasks app.synth to app.run

- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
- java/lambda-cron/src/test/java/software/amazon/awscdk/examples/LambdaCronStackTest.java
- java/lambda-cron/src/test/resources/software/amazon/awscdk/examples/testCronLambdaExpected.json
***Description of changes:***
**1. Updated unit tests to make sure the assertions were running.**
As one of them didn't actually assert anything (`testTypes`). Whilst there, I also fixed some of the tests and the `actual` and `expected` were the wrong way around, unless using hamcrest's `assertThat` (which it now is).
**2. Fixed deployment by removing the function name.**
**Before**
The function name was invalid, although it passed CFT validation, it resulted in:
```
3/6 | 11:14:26 PM | CREATE_FAILED        | AWS::Lambda::Function   | SingletonLambdac4f9439a61bd48c9859d3e91a657e2cb (SingletonLambdac4f9439a61bd48c9859d3e91a657e2cbF7A8D345) 1 validation er
ror detected: Value 'CDK Lambda Cron Example' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression …
```
> Fixes an invalid function name in the lambda-cron Java example

- typescript/api-cors-lambda-crud-dynamodb/index.ts
- typescript/appsync-graphql-dynamodb/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/index.ts
- typescript/my-widget-service/widget_service.ts
- typescript/static-site/static-site.ts
https://github.com/aws-samples/aws-cdk-examples/issues/99
Changes the behaviour of examples that create S3 Buckets and DynamoDB Tables such that these resources are deleted by cdk destroy. Explains the behaviour in comments
> sets removal policy on S3 and DynamoDB to DESTROY

- README.md
- python/lambda-s3-trigger/app.py
- python/lambda-s3-trigger/cdk.json
- python/lambda-s3-trigger/lambda/lambda-handler.py
- python/lambda-s3-trigger/requirements.txt
- python/lambda-s3-trigger/s3trigger/s3trigger_stack.py
**Description of changes**  
Added sample for s3 trigger for lambda
> feat: Add s3 trigger for lambda

- README.md
- python/api-cors-lambda/app.py
- python/api-cors-lambda/cdk.json
- python/api-cors-lambda/lambda/lambda-handler.py
This PR will add an example in Python, showing one possible way of creating an API GW Rest API, with an /example endpoint (method: GET), with CORS enabled.
Should be fairly straight forward to modify and expand.
There's a similar example in typescript, although this one is a bit more simplifed, and is in Python (Which lacks examples IMHO).
CORS functionality was Tested locally, as well as by using https://www.test-cors.org/.
> feat: Added Python example - API GW with lambda integration and CORS enabled

- typescript/appsync-graphql-dynamodb/index.ts
*Issue #, if available:* How managed policies are referenced has recently changed, this caused a breaking change. This PR fixes a specific example raised in an issue.
https://github.com/aws-samples/aws-cdk-examples/issues/82
> Updated Policy Name to match new parameter format.

- README.md
*Description of changes:* Added reference to doc that provides guidance on how to read TypeScript code and translating it to Python.
> Reference to Typescript >Python translation docs

- python/application-load-balancer/app.py
- python/application-load-balancer/httpd.sh
Add httpd user data ,  after deploy , you can access sample web site though application load balancer dns name.
> Update python application-load-balancer example

- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/fargate-load-balanced-service/app.py
- python/ecs/fargate-service-with-autoscaling/app.py
- typescript/ecs/ecs-load-balanced-service/index.ts
- typescript/ecs/fargate-load-balanced-service/index.ts
- typescript/ecs/fargate-service-with-auto-scaling/index.ts
- typescript/ecs/fargate-service-with-local-image/index.ts
Updating several Fargate examples for TypeScript and Python based on breaking change in https://github.com/aws/aws-cdk/pull/3719.
Fixes #125
---
> fix: Update Fargate LoadBalance Service examples

- typescript/static-site/static-site.ts
Update after this breaking change in 1.9.0: https://github.com/aws/aws-cdk/commit/2ce4a87
---
> fix: update static site example after breaking changes

- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/fargate-load-balanced-service/app.py
- python/ecs/fargate-service-with-autoscaling/app.py
- typescript/ecs/ecs-load-balanced-service/index.ts
- typescript/ecs/fargate-load-balanced-service/index.ts
- typescript/ecs/fargate-service-with-auto-scaling/index.ts
- typescript/ecs/fargate-service-with-local-image/index.ts
broke because of this change: https://github.com/aws/aws-cdk/pull/4213
Fixes #137
---
> fix: update ecs examples

- typescript/ecs/fargate-service-with-local-image/index.ts
Updated the ecs examples to use the latest version of the cdk.
Fixes # 
---
> fix: update ecs-patterns examples to use the latest version of the cdk

- typescript/api-cors-lambda-crud-dynamodb/index.ts
- typescript/api-cors-lambda-crud-dynamodb/package.json
- typescript/application-load-balancer/package.json
- typescript/appsync-graphql-dynamodb/package.json
- typescript/classic-load-balancer/package.json
- typescript/custom-resource/package.json
- typescript/lambda-cron/package.json
- typescript/my-widget-service/package.json
- typescript/my-widget-service/widget_service.ts
- typescript/resource-overrides/package.json
- typescript/static-site/package.json
- typescript/stepfunctions-job-poller/package.json
Node.js 8.x EoL is on 31 Dec 2019 https://endoflife.date/nodejs
Fixes #132
---
> chore: update lambda.Runtime to NODEJS_10_X

- typescript/custom-resource/my-custom-resource.ts
- typescript/lambda-cron/index.ts
The Python version specified in the Lambda runtime has been changed from PYTHON_2_7 to PYTHON_3_6.
> fix: Lambda runtime has been changed from PYTHON_2_7 to PYTHON_3_6

- typescript/ecs/ecs-service-with-advanced-alb-config/index.ts
> chore(ecs): add the usage of "loadBalancerTarget()" when creating target group

- csharp/random-writer/.gitignore
- csharp/random-writer/README.md
- csharp/random-writer/cdk.json
- csharp/random-writer/src/RandomWriter.sln
- csharp/random-writer/src/RandomWriter/Program.cs
- csharp/random-writer/src/RandomWriter/RandomWriter.csproj
- csharp/random-writer/src/RandomWriter/RandomWriterStack.cs
- csharp/random-writer/src/RandomWriter/resources/index.js
> feat: add RandomWriter C# example

- python/ecs/cluster/app.py
- python/url-shortener/cdk.context.json
> fix: update the Python URL shortener example with the new cdk.context.json used by the VPC provider

- java/hello-world/pom.xml
- java/hello-world/src/main/java/software/amazon/awscdk/examples/HelloJavaStack.java
- java/lambda-cron/pom.xml
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
> chore: refresh Java examples with latest syntax elements

- java/resource-overrides/src/test/java/software/amazon/awscdk/examples/ResourceOverridesStackTest.java
Change to just a regular `toString()`, which works the same in this case.
---
> fix(java/resource-overrides): example uses method toPrettyString() which doesn't exist

- java/resource-overrides/src/test/resources/software/amazon/awscdk/examples/testResourceOverrides.expected.json
- scripts/build-java.sh
- scripts/build-npm.sh
- scripts/build-python.sh
The resource-overrides code build was broken because desiredCapacity is
not calculated all of the time.
Ref: https://github.com/aws/aws-cdk/commit/0adf6c75c1f0aa4acc131915970a496326dc559f
Also, outputting the current project being built into STDOUT for better
future diagnosis.
---
> fix: resource-overrides build broken due to changes to CDK autoscaling module

- csharp/capitalize-string/cdk.json
- csharp/elasticbeanstalk/elasticbeanstalk-environment/cdk.json
- csharp/static-site/cdk.json
- Added package-lambda script to capitalize-string
- Added context to elasticbeanstalk-environment
- Added DO_NOT_AUTOTEST to static-site (requires user credentials in code)
- Added context to static-site
Fixes #228  
---
> chore(csharp): update cdk configs for new csharp CI builds

- .travis.yml
Remove the Travis configuration file so Github Actions is the only CI for repo.
---
> chore: remove Travis CI config file

- README.md
This PR fixes a broken link in the README.
The link to the `ecs-network-load-balanced-service` TypeScript example doesn't currently resolve as it's missing "network-" in the URL.
I didn't open an issue to link this to as I figured it would be more trouble than it's worth.
---
> fix: Fixes broken link for ecs-network-load-balanced-service example

- .github/workflows/build.yml
Proposing updating the `checkout` action used in the Actions workflow to the latest - `v2`. Details - https://github.com/actions/checkout#checkout-v2
---
> chore: update version of checkout action in workflow

- typescript/cognito-api-lambda/README.md
- typescript/cognito-api-lambda/cdk.json
- typescript/cognito-api-lambda/index.ts
- typescript/cognito-api-lambda/package.json
- typescript/cognito-api-lambda/src/helloworld.ts
- typescript/cognito-api-lambda/tsconfig.json
Typescript example for #244 
This makes a Cognito-protected APIG backed by a simple Hello World Lambda.
Signed-off-by: campionfellin <campionfellin@gmail.com>
---
> feat(newex): example of Cognito-protected APIGateway backed by Lambda

- typescript/cognito-api-lambda/index.ts
- typescript/eks/cluster/index.ts
- typescript/eks/cluster/tsconfig.json
* update Cognito example to incorporate the recent breaking change.
* eks/cluster typescript project to exclude re-compiling dependencies in
`node_modules/`.
Fixes # 
---
> fix: broken build

- csharp/random-writer/src/RandomWriter/RandomWriter.csproj
CDK and JSII versions were not pinned and the latest release included breaking changes.
Also modified the dependencies to be pinned to the latest version
---
> fix: csharp example RandomWriter does not work

- csharp/capitalize-string/src/CapitalizeString/CapitalizeString.csproj
- csharp/classic-load-balancer/src/ClassicLoadBalancer/ClassicLoadBalancer.csproj
- csharp/elasticbeanstalk/elasticbeanstalk-bg-pipeline/src/ElasticbeanstalkBgPipeline/ElasticbeanstalkBgPipeline.csproj
- csharp/elasticbeanstalk/elasticbeanstalk-environment/src/ElasticbeanstalkEnvironment/ElasticbeanstalkEnvironment.csproj
- csharp/stepfunctions-job-poller/src/StepfunctionsJobPoller/StepfunctionsJobPoller.csproj
Rationale: these should work with the latest release and also serve as a canary
if they break.
---
> chore: remove pinned dependencies for csharp examples

- python/existing-vpc-new-ec2-ebs-userdata/cdk_vpc_ec2/cdk_vpc_ec2_stack.py
> fix: indicate port 80 is http NOT ssh

- typescript/static-site/static-site.ts
<refactor>
Update deprecated method `AddressRecordTarget `
[Use RecordTarget](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_route53/AddressRecordTarget.html)
> refactor: replace deprecated method

- typescript/elasticbeanstalk/elasticbeanstalk-environment/index.ts
Fixes # 
- Fix the beanstalk dependency so that app creation happens before the environment creation.
---
> feat: add `dependsOn` for beanstalk environment

- .gitignore
- csharp/random-writer/src/RandomWriter/RandomWriter.csproj
- scripts/build-npm.sh
- typescript/lambda-api-ci/.gitignore
- typescript/lambda-api-ci/.npmignore
- typescript/lambda-api-ci/.prettierrc
- typescript/lambda-api-ci/README.md
- typescript/lambda-api-ci/bin/ci.ts
- typescript/lambda-api-ci/bin/lambda.ts
- typescript/lambda-api-ci/buildspec.yml
- typescript/lambda-api-ci/cdk.json
- typescript/lambda-api-ci/jest.config.js
- typescript/lambda-api-ci/lib/ci-stack.ts
- typescript/lambda-api-ci/lib/lambda-api-stack.ts
- typescript/lambda-api-ci/package.json
- typescript/lambda-api-ci/src/handler.ts
- typescript/lambda-api-ci/src/package.json
- typescript/lambda-api-ci/tsconfig.json
I'm adding an example here that deploys a Lambda+ApiGateway setup using CodePipeline. 
Although there's plenty of examples of Lambda already, deploying them via CodePipeline had some non-trivial challenges to sort out. This could mean teams start using CDK and like it, but drop it because they can't adopt Full CI/CD easily when using it
Fixes #267 
---
> Add a Lambda+Codepipeline Typescript example

- java/static-site/src/main/java/software/amazon/awscdk/examples/StaticSiteStack.java
Fixes #284:  the constructs are unable to find the stack they are defined in.
---
> fix: StaticSiteStack does not extend Stack

- .github/workflows/close-stale-issues.yml
- Sends a warning and then closes issues that haven't gotten a response in 2 years.
- Adds a closing-soon label to issues that have had the response-requested label for a week with no response.
- Sends a warning and then closes issues that have a closing-soon label and haven't had a response in 4 days.
---
> chore(repo): Add stale github action

- java/ecs/fargate-load-balanced-service/src/test/resources/com/amazonaws/cdk/examples/expected.cfn.json
The ordering of tags in the CDK was changed to be alphabetical in
https://github.com/aws/aws-cdk/pull/7913. This change updates the
expected result in the Java ECS example to match.
---
> fix: update expected tag order in Java ECS example

- .mergify.yml
This condition enforces that PRs have no comments before it can be
merged. It's not clear why this is needed. As long as the build succeeds
and there is one approval from a core member, it's fine to merge
---
> chore(mergify): remove commented-reviews-by condition

- .gitignore
- typescript/eks/cluster/index.ts
This is due to the breaking change in the eks module introduced in
version 1.50.0.
https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#1500-2020-07-07
Fixes # 
---
> fix(typescript/eks): compile fails for missing property 'version'

- python/docker-app-with-asg-alb/dockerized_app_cdk/rds_stack.py
- python/new-vpc-alb-asg-mysql/cdk_vpc_ec2/cdk_rds_stack.py
- python/rds/app.py
Upgrades to the engine version specification from the RDS package.
---
> fix(python/rds): update to new API

- java/ecs/fargate-load-balanced-service/src/test/resources/com/amazonaws/cdk/examples/expected.cfn.json
Version [1.62.0](https://github.com/aws/aws-cdk/releases/tag/v1.62.0) of the cdk introduced this [PR](https://github.com/aws/aws-cdk/pull/9986):
- Changed load balancer deletion protection to also set the attribute to false, instead of omitting the attribute when deletionProtection is false.
The other change in the diff seems like just a shift in the location inside the template, not an actual change. 
---
> chore(java): update expectation for fargate-load-balanced-service example

- python/docker-app-with-asg-alb/dockerized_app_cdk/rds_stack.py
- python/new-vpc-alb-asg-mysql/cdk_vpc_ec2/cdk_rds_stack.py
- python/rds/app.py
- typescript/eks/cluster/index.ts
Updates example to use the breaking changes introduced in CDK v1.65.0
eks: `addAutoScalingGroup` was renamed to `connectAutoScalingGroupCapacity`.
rds: the `master_username` and `master_password` properties were renamed to
`login` and are also now optional. dropped them from the example to simplify.
[Release notes for 1.65.0](https://github.com/aws/aws-cdk/releases/tag/v1.65.0)
---
> chore: fix examples that are affected by breaking changes in 1.65.0

- python/ecs/fargate-service-with-autoscaling/app.py
aws-cdk-examples/python/ecs/fargate-service-with-autoscaling/app.py is throwing following a type error, due to improper function arguments
This PR fixes the invalid  arguments in  AutoScalingFargateService.__init__()
Fixes #332 
---
> fix(python/ecs):  Fix AutoScalingFargateService.__init__()

- python/appsync-graphql-dynamodb/app_sync_cdk/app_sync_cdk_stack.py
see the issue for details
Closes #335
---
> fix: example appsync-graphql-dynamodb fails due to incorrect policy name

- typescript/eks/cluster/index.ts
> fix: `kubeCtlEnabled` is no longer necessary

- java/resource-overrides/pom.xml
> chore: update Google Guava to address CVE-2020-8908

- java/resource-overrides/src/test/resources/software/amazon/awscdk/examples/testResourceOverrides.expected.json
The change corresponding to https://github.com/aws/aws-cdk/pull/14527
This fixes the 'resource-overrides' project build.
---
> chore: update expectations per latest CDK changes

- python/rekognition-lambda-s3-trigger/rekognition_lambda_s3_trigger/rekognition_lambda_s3_trigger_stack.py
feat: Add specific suffixes for image types supported by Amazon Rekognition
Fixes # 
---
> feat: update rekognition_lambda_s3_trigger_stack.py

- java/resource-overrides/src/main/java/software/amazon/awscdk/examples/ResourceOverridesStack.java
Can't just assume any construct will be of the right type, needs a type
check.
Fixes # 
---
> chore: fix Java overrides test

- python/ec2/instance/app.py
The policy AmazonEC2RoleforSSM should be replaced by AmazonSSMManagedInstanceCore and will be deprecated soon.
Old role:
arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
New role:
arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
(the new role arn drops the /service-role path) 
Fixes #428
---
> fix: Replace deprectated role

- .github/workflows/build-pull-request.yml
- scripts/build.sh
This PR fixes an issue thrown in the cdk-ops CI:
```shell
[Container] 2021/07/02 13:07:11 Running command chmod +x scripts/*.sh && scripts/build.sh
/codebuild/output/tmp/script.sh: line 4: scripts/build.sh: No such file or directory
```
This was being thrown because the `scripts/build.sh` file was deleted in a previous commit to the `aws-cdk-examples` repo in an effort to optimize build times.
See:
- https://github.com/aws-samples/aws-cdk-examples/pull/463
- https://github.com/aws-samples/aws-cdk-examples/commit/b690f003b0aaa443920c1e714b4fc230aa5f76fb
To resolve this issue I recreated the `scripts/build.sh` and moved the condition logic implemented in `.github/workflows/build-pull-request.yml` to the `build.sh`.
> fix(ci): moved condition logic from github "build" workflow to `scripts/build.sh`

- typescript/eks/cluster/index.ts
fix: update the props of AutoScalingGroup `updateType: autoscaling.UpdateType.ROLLING_UPDATE` to `updatePolicy: autoscaling.UpdatePolicy.rollingUpdate()`
fix: update eks cluster and dataplane node version to 1.21.
EKS 1.16 will `End of support` at September 27, 2021. 
see: [source](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
| Kubernetes version | Upstream release | Amazon EKS release | Amazon EKS end of support | 
| --- | --- | --- | --- | 
| 1\.16 | September 8, 2019 | April 30, 2020 | September 27, 2021 | 
| 1\.17 | December 9, 2019 | July 10, 2020 | November 2, 2021 | 
| 1\.18 | March 23, 2020 | October 13, 2020 | February 18, 2022 | 
| 1\.19 | August 26, 2020 | February 16, 2021 | April, 2022 | 
| 1\.20 | December 8, 2020 | May 18, 2021 | July, 2022 | …
> fix(typescript/eks/cluster): fix BC

- .github/ISSUE_TEMPLATE/feature-request.yml
This PR removes the requirement to check the boxes in the "Acknowledge" section of feature-request issues.
---
> fix(GitHub issue templates): remove requirement from "Acknowledge" section

- csharp/application-load-balancer/src/ApplicationLoadBalancer/ApplicationLoadBalancer.csproj
- csharp/appsync-graphql-dynamodb/src/AppsyncGraphqlDynamodb/AppsyncGraphqlDynamodb.csproj
- csharp/my-widget-service/cdk.json
- csharp/my-widget-service/src/MyWidgetService/MyWidgetService.csproj
- csharp/static-site/src/StaticSite/StaticSite.csproj
Upgrade C# examples; the current examples fail to build due to outdated versions of jsii.
---
> chore: upgrading C# examples to latest CDK and netcoreapp3.1.

- java/alb-multi-rule-response/pom.xml
- java/classic-load-balancer/pom.xml
- java/codebuild/project/pom.xml
- java/codebuild/project/src/main/java/com/myorg/ProjectStack.java
- java/codebuild/reportgroup/pom.xml
- java/codebuild/sourceCredential/pom.xml
- java/custom-resource/pom.xml
- java/ecs/fargate-load-balanced-service/pom.xml
- java/hello-world/pom.xml
- java/lambda-cron/pom.xml
- java/my-widget-service/pom.xml
- java/resource-overrides/pom.xml
- java/static-site/pom.xml
- java/stepfunctions-job-poller/pom.xml
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project project: An exception occured while executing the Java class. Invalid S3 bucket name (value: s3BucketName)
[ERROR] Bucket name must only contain lowercase characters and the symbols, period (.) and dash (-) (offset: 2)
[ERROR] Error: Invalid S3 bucket name (value: s3BucketName)
```
Fixed the above error, and while I was at it, upgraded the CDK version(s) for all of the Java examples.
> chore: fix java build break (s3 bucket name) and upgrade CDK version

- python/new-vpc-alb-asg-mysql/cdk_vpc_ec2/cdk_rds_stack.py
Fixed issue #539: rds subnet groups are not assigned to the DB subnet.
Fixes #539
---
> fix: Fixed issue #539: rds subnet groups are not assigned to the DB subnet

- java/ecs/fargate-load-balanced-service/src/test/resources/com/amazonaws/cdk/examples/expected.cfn.json
`com.amazonaws.cdk.examples.ECSFargateLoadBalancedStackTest` is currently broken because the expected template is stale. 
This [PR](https://github.com/aws/aws-cdk/pull/17865) in the CDK, along with the migration of the examples to v2, made it so the `DesiredCount` property is now not part of the template. This is the expected behavior. 
---
> fix: wrong expected template for java esc example

- README.md
Follow-up to https://github.com/aws-samples/aws-cdk-examples/commit/ee354a31dcfe374f3fad8e9406210a8f109daf5c - adding https://github.com/aws-samples/aws-cdk-examples/tree/master/go to the list of examples here.
Fixes https://github.com/aws-samples/aws-cdk-examples/issues/544
---
> docs: README - add Go examples

- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
- java/lambda-cron/src/test/resources/software/amazon/awscdk/examples/testCronLambdaExpected.json
`cdk deploy` of the example fails due to `python2.7` no longer being supported. Updated lambda runtime to latest `python 3.9`
Fixes # [616](https://github.com/aws-samples/aws-cdk-examples/issues/616)
---
> fix: updated lambda runtime to python3_9

- typescript/static-site/index.ts
- typescript/static-site/static-site.ts
*Requesting @peterwoodworth review this please*
This PR addresses an issue that was introduced in PR #625... the issue is related to the placement of the ViewerCertificate attributes in a Distribution resource.  From below we see the original synthesized CFN
```
"StaticSiteSiteDistributionE3AF6299": {
"Type": "AWS::CloudFront::Distribution",
"Properties": {
"DistributionConfig": {
"Aliases": [
...
],
"DefaultCacheBehavior": {
...
"Origins": [
...
],
"ViewerCertificate": {
"AcmCertificateArn": {
"Fn::GetAtt": [
"StaticSiteSiteCertificateCertificateRequestorResourceB92D481B",
"Arn"
]
},
"MinimumProtocolVersion": "TLSv1.2_2021",
"SslSupportMethod": "sni-only"
}
},
"ViewerCertificate": {
"MinimumProtocolVersion": "TLS_V1_1_2016",
"SslSupportMethod": "sni-only"
}
},
},
```
From the above, …
> fix: Addressed issue where distribution ViewerCertificate attributes were being placed in wrong place in Distribution hierarchy

- .mergify.yml
This PR removes semantic checks from the Mergify config. Semantic Pull Request's service is currently down and we need to unblock PRs.
---
> ci(mergify): removed semantic checks

- typescript/s3-object-lambda/package.json
Currently, the pipeline that builds these packages is failing because the `s3-object-lambda` example assumes that there is only one version of the CDK; this forces it to use v1. This example should be migrated to v2 in the future. 
---
> chore: force the version in an example to be V1

- typescript/rds/aurora/aurora.ts
The code was bypassing null-checks, which of course led to
passing an `undefined` value which breaks the CDK synthesis.
---
> chore: fix broken build in RDS Aurora example

- java/ecs/fargate-load-balanced-service/src/main/java/com/amazonaws/cdk/examples/ECSFargateLoadBalancedStack.java
- java/ecs/fargate-load-balanced-service/src/test/resources/com/amazonaws/cdk/examples/expected.cfn.json
- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/ecs-service-with-advanced-alb-config/app.py
- typescript/ecs/ecs-network-load-balanced-service/index.ts
- typescript/ecs/ecs-service-with-advanced-alb-config/index.ts
- typescript/rds/aurora/aurora.ts
This issue addresses the bug found in #695.
The fix adds an ingress rule to the ASG security group that allows connectivity from the load balancer.
The issue was that the default security group of the autoscaling group did not have any ingress rules which led to the ALB being unable to connect to the ECS service (and subsequently showing a 503 or 504 error).
An additional change was made to set the host-port to '0' which allows ECS to define any host port to host the service.
I am also validating the following examples which have load balancers:
**Python**
| Example | Status | Notes |
| -- | -- | -- |
|[ecs-load-balanced-service](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/ecs-load-balanced-service) | Needed fix | ASG ingress rule added for connection from …
> Fix: (#695) Fixed security groups to properly route traffic from ALB to ASG

- typescript/lambda-cron/index.ts
- typescript/lambda-cron/lambda-cron.test.ts
Received the following error when deploying CDK:
```
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions.
```
Updating Python version. Deployed successfully and tested Lambda function.
Fixes # 
---
> fix(python) lambda cron runtime

- java/resource-overrides/src/main/java/software/amazon/awscdk/examples/ResourceOverridesStack.java
Signed-off-by: Vinayak Kukreja <vinakuk@amazon.com>
Currently the build is failing with the error,
```
java.lang.IllegalArgumentException: Expected value.get(0) to be one of: software.amazon.awscdk.services.s3.CfnBucket.AnalyticsConfigurationProperty, software.amazon.awscdk.IResolvable; received class com.google.common.collect.RegularImmutableMap
```
This PR fixes the error by returning AnalyticsConfigurationProperty instead of ImmutableMap.
Fixes # https://github.com/aws-samples/aws-cdk-examples/issues/732
---
> fix(java/resource-overrides): return AnalyticsConfigurationProperty instead of ImmutableMap

- java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceStack.java
- java/my-widget-service/src/test/resources/software/amazon/awscdk/examples/testMyWidgetServiceExpected.json
CloudFormation templates in aws-cdk-examples have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs10.x). The affected templates have been updated to a supported runtime (nodejs16.x).
Fixes #439 
---
> fix: Update java/my-widget-service to node 16

- java/hello-world/pom.xml
- java/hello-world/src/test/java/software/amazon/awscdk/examples/JDK9.java
- java/hello-world/src/test/java/software/amazon/awscdk/examples/SinkQueueTest.java
This test broke because a recent release added a dependency. 
Just check the important part of the template using the `assertions` library.
---
> fix: Java snapshot test is too brittle

- java/hello-world/src/test/java/software/amazon/awscdk/examples/SinkQueueTest.java
Latest jsii v1.70.0 changes the way it throws errors. We are expecting a `jsii.jsiiException` but getting a `java.lang.runtimeException` now. This was never the intention of the jsiiException api, so changing this to the more generic runtimeException.
---
> fix: latest jsii breaks assert on jsiiException  

- java/resource-overrides/src/test/resources/software/amazon/awscdk/examples/testResourceOverrides.expected.json
After https://github.com/aws/aws-cdk/pull/22819, the service principal always resolves to 'service.amazonaws.com'.
---
> fix: ResourceOverridesStackTest is failing after service principals logic update

- csharp/CloudFront-S3-WAF/src/src.csproj
- csharp/apigateway-cognito-lambda-dynamodb/src/CDK/cdk.csproj
- csharp/apigateway-cognito-lambda-dynamodb/src/Lambda/AuthFunction/AuthFunction.csproj
- csharp/apigateway-cognito-lambda-dynamodb/src/Lambda/BackendFunction/BackendFunction.csproj
- csharp/application-load-balancer/src/ApplicationLoadBalancer/ApplicationLoadBalancer.csproj
- csharp/appsync-graphql-dynamodb/src/AppsyncGraphqlDynamodb/AppsyncGraphqlDynamodb.csproj
- csharp/capitalize-string/CapitalizeStringHandler/src/CapitalizeStringHandler/CapitalizeStringHandler.csproj
- csharp/capitalize-string/CapitalizeStringHandler/src/CapitalizeStringHandler/aws-lambda-tools-defaults.json
- csharp/capitalize-string/CapitalizeStringHandler/test/CapitalizeStringHandler.Tests/CapitalizeStringHandler.Tests.csproj
- csharp/capitalize-string/README.md
- csharp/capitalize-string/src/CapitalizeString/CapitalizeString.csproj
- csharp/capitalize-string/src/CapitalizeString/CapitalizeStringStack.cs
- csharp/classic-load-balancer/src/ClassicLoadBalancer/ClassicLoadBalancer.csproj
- csharp/elasticbeanstalk/elasticbeanstalk-bg-pipeline/src/ElasticbeanstalkBgPipeline/ElasticbeanstalkBgPipeline.csproj
- csharp/elasticbeanstalk/elasticbeanstalk-environment/src/ElasticbeanstalkEnvironment/ElasticbeanstalkEnvironment.csproj
- csharp/eventbridge-firehose-s3-cdk/src/src.csproj
- csharp/lambda-cron/src/LambdaCron.Tests/LambdaCron.Tests.csproj
- csharp/lambda-cron/src/LambdaCron/LambdaCron.csproj
- csharp/my-widget-service/cdk.json
- csharp/my-widget-service/src/MyWidgetService/MyWidgetService.csproj
- csharp/random-writer/src/RandomWriter/RandomWriter.csproj
- csharp/static-site/src/StaticSite/StaticSite.csproj
- csharp/stepfunctions-job-poller/src/StepfunctionsJobPoller/StepfunctionsJobPoller.csproj
.NET Core 3.1 is EOL
https://endoflife.date/dotnet
And the jsii/superchain image only ships with supported versions, so this fixes the failing main build.
---
> chore: upgrade dotnet projects to use .NET 6.0

- go/ecs/cluster/README.md
Found a typo in the ECS Cluster README - this PR corrects it. 
#811 
---
> CDK Go - Fixing README Typo

- typescript/rds/mysql/mysql.ts
The template was invalid JSON as the username wasn't enclosed in quotes. Running JSON.stringify instead of manually creating the JSON makes more sense too. 
Fixes #735
---
> Fix secretStringTemplate in mysql example

- scripts/build-python.sh
We need to clean out the pip venv between project builds, or we inherit a mess if _anything_ is pinned at all.
Fixes #837
---
> Clean the python venv between project builds

- .github/workflows/build-pull-request.yml
- scripts/build-csharp.sh
- scripts/build-go.sh
- scripts/build-java.sh
- scripts/build-python.sh
- scripts/build-typescript.sh
This PR fixes the CI build process to only attempt to synth cdk apps that have code that actually changed, instead of building all of apps for a particular language.
Fixes # 
---
> feat: test build only on changed code

- .github/workflows/build-pull-request.yml
Fixes github warning. Removed as those lines are not needed at this time.
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
> fix: github set-output deprecated

- .github/workflows/build-pull-request.yml
- scripts/build-python.sh
This uses the github matrix to run each language build in parallel.
it does so by filtering out the files that are only used by that language. 
In addition to parallelizing the builds, it gives each Python build its own venv, as Python is the only language that does not have local packages by default. 
---
> feat(build): Parallelize the build step

- typescript/cognito-api-lambda/index.ts
fixes #880.
Update the Lambda runtime to NodeJS 18 so it can be deployed.
Fixes #880
---
> Update NodeJS runtime to use a non-deprecated version

- python/s3-sns-sqs-lambda-chain/s3_sns_sqs_lambda_chain/s3_sns_sqs_lambda_chain_stack.py
Fixes #884 
Duplicate parameter visibilityTimeout in  `python/s3-sns-sqs-lambda-chain/s3_sns_sqs_lambda_chain/s3_sns_sqs_lambda_chain_stack.py`
---
> remove duplicate visibility timeout, explicitly use Duration type

- scripts/build-typescript.sh
https://github.com/aws-samples/aws-cdk-examples/blob/2a494c4c30ff58bcc16b6e338cb704b16329e4aa/.github/workflows/build-pull-request.yml#L76
The `build-typescript.sh` should just build a single ts project rather than all projects
https://github.com/aws-samples/aws-cdk-examples/blob/2a494c4c30ff58bcc16b6e338cb704b16329e4aa/scripts/build-typescript.sh#L5
This PR fixes this issue and conditionally install the npm packages with yarn or npm command based on the availability of `yarn.lock` and `npm-lock.json`.
---
> fix: update build-typescript.sh

- .github/workflows/build-pull-request.yml
- scripts/build-typescript.sh
This PR fixes the build-typescript.sh that fails when `package.json` is not available such as `typescript/ecs/fargate-service-with-efs` and all changed files under it, we should proceed the install/build/test/synth at `typescript/ecs/fargate-service-with-efs` instead of `typescript/ecs` and check if `package.json` is available at `typescript/ecs/fargate-service-with-efs`.
To achieve this, we should pass full path of the changed files instead of just $part2 from here:
https://github.com/aws-samples/aws-cdk-examples/blob/ef6b8a428593aca854dadae808a7c4a4596e2fd2/.github/workflows/build-pull-request.yml#L76
And allow `build-typescript.sh` to traverse the given full path from top down to proceed the directory where the first package.json comes with.
With this processing logic we can handle:
1. …
> fix: build-typescript.sh fails if package.json is not available 

- typescript/custom-resource/custom-resource-handler.py
Fixing the property name in the input event JSON as the `custom-resource-handler.py` lambda throws the following error:
```
[ERROR]	2023-10-05T16:16:39.193Z	xxxx-xxx-xxx-xxx-xxxx	'Message'
Traceback (most recent call last):
File "/var/task/index.py", line 17, in main
message = event['ResourceProperties']['Message']
KeyError: 'Message'
```
I have preferred not changing the interface (maintaining the camel case), but changing the dict directly as it was just one correction VS two. Let me know.
BR
Luca
---
> Fixing KeyError in CustomResource lambda

- typescript/application-load-balancer/README.md
- typescript/application-load-balancer/index.ts
- typescript/classic-load-balancer/README.md
- typescript/classic-load-balancer/index.ts
Updated Classic and Application Load Balancer's instance family to latest 4th Generation of Burstable instances
Updated Classic and Application Load Balancer's AMI to Amazon Linux 2023 from EOL Amazon Linux
---
> Updated load balancer's instance to latest gen

- python/batch/batch-arm64-instance-type/app.py
To solve this "arm-based instance type cannot be used with other instance types., " this error, removed optimal instance option.
Fixes # arm-based instance type cannot be used with other instance types., 
---
> fix(python/batch-arm64-instance-type): removed optimal instance classes with ARM base batch cluster

- typescript/static-site/static-site.ts
This pull request addresses a runtime error encountered in one of the TypeScript examples due to the missing import statement for the `path` module. By adding `import path = require('path');`, this change ensures the application can correctly utilize the `path` module's functionalities, thus maintaining the stability and functionality of the example.
`cdk diff -c accountId=123456789 -c domain=mystaticsite.com -c subdomain=www`
2.128.0 (build d995261)
just add 
`import path = require('path');`
none
> Add Missing path Import to TypeScript Example

- csharp/my-widget-service/src/MyWidgetService/resources/widgets.js
- java/my-widget-service/resources/widgets.js
- typescript/api-cors-lambda-crud-dynamodb/index.ts
- typescript/api-cors-lambda-crud-dynamodb/lambdas/create.ts
- typescript/api-cors-lambda-crud-dynamodb/lambdas/delete-one.ts
- typescript/api-cors-lambda-crud-dynamodb/lambdas/get-all.ts
- typescript/api-cors-lambda-crud-dynamodb/lambdas/get-one.ts
- typescript/api-cors-lambda-crud-dynamodb/lambdas/package.json
- typescript/api-cors-lambda-crud-dynamodb/lambdas/update-one.ts
- typescript/appsync-graphql-eventbridge/index.ts
- typescript/lambda-layer/lib/lambda-layer-stack.ts
- typescript/my-widget-service/resources/widgets.js
- typescript/my-widget-service/widget_service.ts
- typescript/rekognition-lambda-s3-trigger/lambda/rekfunction.ts
- typescript/rekognition-lambda-s3-trigger/lib/rekognition-lambda-s3-trigger-stack.ts
- typescript/rekognition-lambda-s3-trigger/package.json
- typescript/rekognition-lambda-s3-trigger/tsconfig.json
- typescript/s3-object-lambda/lib/s3-object-lambda-stack.ts
- typescript/s3-object-lambda/package.json
- typescript/s3-object-lambda/resources/retrieve-transformed-object-lambda/index.js
Update nodejs version to latest if no aws js sdk is being used.
Update nodejs version to 20 if aws js sdk is being used. So that in the future if aws sdk version does go through another update we could to touch.
Part of: #961
> Fix(typescript): Update nodejs version

- typescript/rds/aurora/aurora.ts
This pull request removes the process.exit(1); 
statement that follows the throw new Error('Unknown Engine Please Use mysql or postgresql'); line. 
The process.exit(1); is unnecessary because once an error is thrown, the execution of the code is halted, and the process.exit(1); will never be reached.
`cdk diff`
2.134.0 (build 265d769)
As you can see just delete
```
process.exit(1);
```
none
By removing the process.exit(1); statement, we can improve the code readability and maintain consistency with the error handling mechanism in the AWS CDK stack definition file. The throw new Error() statement is sufficient to handle the error and stop the execution of the code when an unknown engine is encountered.
> Remove unnecessary process.exit(1); after throw new Error()

- java/my-widget-service/resources/widgets.js
- java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceStack.java
Similar to https://github.com/aws-samples/aws-cdk-examples/pull/1010
Part of: https://github.com/aws-samples/aws-cdk-examples/issues/961
---
> chore(java): update nodejs version to 20.x

- .github/workflows/build-pull-request.yml
- csharp/package.json
- go/package.json
- java/package.json
- python/package.json
- Update !typescript package.json to use at least use stable 2.0
- If not a typescript then install the cdk cli otherwise use the cdk cli version from the ts cdk app. 
---
> Fix: Typescript npm install command and update other language package

- typescript/rds/mysql/mysql.ts
Follow [AWS Prescriptive Guidance - Best practices for using the AWS CDK in TypeScript to create IaC projects](https://docs.aws.amazon.com/prescriptive-guidance/latest/best-practices-cdk-typescript-iac/typescript-best-practices.html#var-keyword).
Replace variable declarations using `var` with `let`.
Fixes #1077 
---
> Don't use the "var" keyword.

- typescript/imagebuilder/lib/imagebuilder-stack.ts
> Chore: Fix spelling

- .github/workflows/build-pull-request.yml
Pin the Github action tj-actions/changed-files to version e9772d140489982e0e3704fea5ee93d536f1e275
---
> Chore: pin tj-actions/changed-files

- typescript/connect-cdk/.gitignore
- typescript/connect-cdk/.npmignore
- typescript/connect-cdk/README.md
- typescript/connect-cdk/bin/connect_cdk.ts
- typescript/connect-cdk/callFlows/MainFlow.json
- typescript/connect-cdk/cdk.json
- typescript/connect-cdk/hellolambda/lambda_function.py
- typescript/connect-cdk/jest.config.js
- typescript/connect-cdk/lib/connect_cdk-stack.ts
- typescript/connect-cdk/package.json
- typescript/connect-cdk/test/connect_cdk_simple.test.ts
- typescript/connect-cdk/tsconfig.json
Example using the CDK to fully create a simple Amazon Connect solution, including a call flow integrated with a Lambda function.
---
> Connect With Flows and Lambda Integration

- typescript/static-site/static-site.ts
Updated the `typescript/static-site` example with:
- replaced `cloudfront_origins.S3Origin` with `cloudfront_origins.S3BucketOrigin`
- converted to usage of `OriginAccessControl` instead of `OriginAccessIdentity` for `cloudfront` to access `S3`, according to  [CloudFront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#migrate-from-oai-to-oac)
While this example is marked not to be auto-tested, the typescript code runs and I can confirm that the stack deploys on a test account where the previous version did as well.
Fixes #1084
---
> typescript/static-site: S3Origin -> S3BucketOrigin

- python/lambda-from-container/README.md
- python/lambda-from-container/app.py
> Fix(py/lambda-from-container): Fixes #715 for ecr repo arn

- csharp/capitalize-string/src/CapitalizeString/CapitalizeString.csproj
- csharp/capitalize-string/src/CapitalizeString/CapitalizeStringStack.cs
> Fix(csharp/capitalize): Fix the runtime, update cdk, and ensure that it deploys

- python/application-load-balancer/app.py
> Feat(py/alb): Add example for adding redirect from port 80 to 443

- go/httpapi-lambda/README.md
- go/restapi-lambda/README.md
- go/restapi-sqs/README.md
Fixes # https://github.com/aws-samples/aws-cdk-examples/issues/1122
---
> chore(docs): fix typo

- typescript/elasticbeanstalk/elasticbeanstalk-environment/README.md
- typescript/elasticbeanstalk/elasticbeanstalk-environment/cdk.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-environment/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/tsconfig.json
Fixes #1126 
1. Added creation of an instance role for the Elastic Beanstalk Environment
2. Updated context platform and solution versions
3. Upgrade CDK version to  the latest: 2.188.0
4. Updated README.md to add AWS CLI commands to query available EB platform and solution.
---
> Fix Issue #1126 - the race condition of instance role and eb environment

- .github/workflows/build-pull-request.yml
- typescript/ec2-instance-connect-endpoint/package.json
- typescript/ec2-instance/.gitignore
- typescript/ec2-instance/lib/constructs/server.ts
- typescript/ec2-instance/lib/constructs/vpc.ts
- typescript/ec2-instance/lib/ec2-stack.ts
- typescript/ec2-instance/lib/resources/server/assets/sample/sample.txt
- typescript/ec2-instance/lib/resources/server/config/amazon-cloudwatch-agent.json
- typescript/ec2-instance/lib/resources/server/config/config.sh
- typescript/ec2-instance/lib/utils/env-validator.ts
- typescript/ec2-instance/package.json
- typescript/ec2-instance/tsconfig.json
- typescript/opensearch/cwlogs_ingestion/package.json
> feat: update packages

- java/eks/fargate-cluster/pom.xml
- java/eks/fargate-cluster/src/main/java/com/amazonaws/cdk/EksFargateStack.java
- java/eks/fargate-cluster/src/test/java/com/amazonaws/cdk/EksFargateStackTest.java
- java/eks/fargate-cluster/src/test/resources/com/amazonaws/cdk/EksFargateStackExpected.json
- java/eks/private-cluster/README.md
- java/eks/private-cluster/pom.xml
- java/eks/private-cluster/src/main/java/com/amazonaws/cdk/examples/EksPrivateClusterStack.java
- java/eks/private-cluster/src/test/java/com/amazonaws/cdk/examples/EksPrivateClusterStackTest.java
* Update support for [Amazon EKS 1.32](https://aws.amazon.com/about-aws/whats-new/2025/01/amazon-eks-eks-distro-kubernetes-version-1-32/)
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.KubernetesVersion.html
- https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/eks/package-summary.html#quick-start-heading
- https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/eks/package-summary.html#kubectl-support-heading
> Required aws-cdk v2.179.0+ to support Amazon EKS 1.32+
> * https://github.com/aws/aws-cdk/releases/tag/v2.179.0
---
> chore(java/eks): refresh sample code and set Amazon EKS version as 1.32

- java/eks/fargate-cluster/src/test/resources/com/amazonaws/cdk/EksFargateStackExpected.json
- java/eks/private-cluster/src/main/java/com/amazonaws/cdk/examples/EksPrivateClusterStack.java
- typescript/eks/cluster/index.ts
Update IAM requirements for Amazon EKS to use [AmazonEC2ContainerRegistryPullOnly](AmazonEC2ContainerRegistryPullOnly) only.
Furthermore, [AmazonEC2ContainerRegistryReadOnly](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryReadOnly.html) does not have required permission for [Pull-through Cache (PTR)](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html), where [AmazonEC2ContainerRegistryPullOnly](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryPullOnly.html) does.
Related discussion:
* https://github.com/aws/karpenter-provider-aws/issues/7956
* https://github.com/aws/karpenter-provider-aws/pull/7963
* https://github.com/eksctl-io/eksctl/issues/8318
* …
> chore(iam): follow the best practice to use "AmazonEC2ContainerRegistryPullOnly" only

- python/api-sqs-lambda/api_sqs_lambda/api_sqs_lambda_stack.py
3_7 -> 3_11
fix the python 3.7 unsupported problem
"The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. "
Fixes # 
---
> Update api_sqs_lambda_stack.py -- fix the python 3.7 unsupported problem
