aws-samples/aws-cdk-examples

- .gitignore
- CONTRIBUTING.md
> Update CONTRIBUTING doc

- typescript/.gitignore
- typescript/static-site/README.md
- typescript/static-site/cdk.json
- typescript/static-site/index.ts
- typescript/static-site/package-lock.json
- typescript/static-site/package.json
- typescript/static-site/static-site.ts
- typescript/static-site/tsconfig.json
Example for HTTPS static site infrastructure: S3 bucket, CloudFront distribution, Route53 alias record
> Static site example

- README.md
- typescript/ecs/ecs-service-with-task-placement/cdk.json
- typescript/ecs/ecs-service-with-task-placement/index.ts
- typescript/ecs/ecs-service-with-task-placement/package-lock.json
- typescript/ecs/ecs-service-with-task-placement/package.json
- typescript/ecs/ecs-service-with-task-placement/tsconfig.json
> Add ECS Service with Task Placement example

- typescript/ecs/cluster/index.ts
- typescript/ecs/cluster/package-lock.json
- typescript/ecs/cluster/package.json
- typescript/ecs/ecs-load-balanced-service/index.ts
- typescript/ecs/ecs-load-balanced-service/package-lock.json
- typescript/ecs/ecs-load-balanced-service/package.json
- typescript/ecs/ecs-service-with-advanced-alb-config/index.ts
- typescript/ecs/ecs-service-with-advanced-alb-config/package-lock.json
- typescript/ecs/ecs-service-with-advanced-alb-config/package.json
- typescript/ecs/ecs-service-with-task-placement/index.ts
- typescript/ecs/ecs-service-with-task-placement/package-lock.json
- typescript/ecs/ecs-service-with-task-placement/package.json
- typescript/ecs/fargate-load-balanced-service/package-lock.json
- typescript/ecs/fargate-load-balanced-service/package.json
> Fix ECS examples

- README.md
- typescript/classic-load-balancer/cdk.json
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/README.md
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/cdk.json
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/resources/blue_green.py
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/tsconfig.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/README.md
- typescript/elasticbeanstalk/elasticbeanstalk-environment/cdk.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-environment/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/tsconfig.json
Added 2 Elastic Beanstalk samples:
1. elasticbeanstalk-bg-pipeline: Performing Blue/Green deployments to Elastic Beanstalk environments with CodePipeline and Lambda
2. elasticbeanstalk-environment: Sample to create an Elastic Beanstalk application and environment
> Added ElasticBeanstalk samples

- README.md
Used example for running TypeScript example.
Added 'cd typescript/my-widget-service' to list of commands.
> Doug aws tweak readme

- README.md
- typescript/ecs/ecs-service-with-task-networking/cdk.json
- typescript/ecs/ecs-service-with-task-networking/index.ts
- typescript/ecs/ecs-service-with-task-networking/package.json
- typescript/ecs/ecs-service-with-task-networking/tsconfig.json
> Add example for ECS service with task networking

- README.md
Changed JavaScript example list to a table. Added a blurb about getting info from link.
> chore (docs): Updated README.md

- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/index.ts
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/package.json
> Fix eb bg pipeline example

- README.md
- typescript/ecs/ecs-service-with-logging/cdk.json
- typescript/ecs/ecs-service-with-logging/index.ts
- typescript/ecs/ecs-service-with-logging/package-lock.json
- typescript/ecs/ecs-service-with-logging/package.json
- typescript/ecs/ecs-service-with-logging/tsconfig.json
- typescript/ecs/fargate-service-with-logging/cdk.json
- typescript/ecs/fargate-service-with-logging/index.ts
- typescript/ecs/fargate-service-with-logging/package-lock.json
- typescript/ecs/fargate-service-with-logging/package.json
- typescript/ecs/fargate-service-with-logging/tsconfig.json
> ECS/Fargate Service with logging

- java/hello-world/README.md
- java/lambda-cron/README.md
Didn't find any applicable.
Tweaked some phrases, for clarity.
> minor wording changes in java readme files

- python/ecs/ecs-load-balanced-service/app.py
- python/ecs/ecs-service-with-advanced-alb-config/app.py
- python/ecs/ecs-service-with-task-placement/app.py
- python/ecs/fargate-load-balanced-service/app.py
- python/ecs/fargate-service-with-autoscaling/app.py
Note that this still doesn't fix #483 but is a precursor to that.
> Updated Python examples to work with 0.33.

- README.md
Proposing adding some sort of "table of contents" to the README - maybe something like this? Makes it easy to navigate.
> README - add table of contents

- typescript/ecs/cluster/index.ts
- typescript/ecs/ecs-load-balanced-service/index.ts
- typescript/ecs/ecs-service-with-advanced-alb-config/index.ts
- typescript/ecs/ecs-service-with-logging/index.ts
- typescript/ecs/ecs-service-with-task-networking/index.ts
- typescript/ecs/ecs-service-with-task-placement/index.ts
- typescript/ecs/fargate-load-balanced-service/index.ts
- typescript/ecs/fargate-service-with-auto-scaling/index.ts
- typescript/ecs/fargate-service-with-local-image/index.ts
- typescript/ecs/fargate-service-with-logging/index.ts
- typescript/resource-overrides/index.ts
> Update VPCProps to use maxAzs

- typescript/api-cors-lambda-crud-dynamodb/index.ts
> remove duplicate line

- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/package.json
> chore: fix build for ElasticBeanStalk TypeScript examples

- typescript/static-site/README.md
- typescript/static-site/index.ts
- typescript/static-site/package.json
- typescript/static-site/site-contents/error.html
- typescript/static-site/site-contents/index.html
- typescript/static-site/static-site.ts
Also fixes a bunch of incorrect changes that were made to get the build running prior to the 1.0 release:
Fixes #102 
Fixes #93 
> feat: include DNS-validated ACM certificate and S3 bucket deployment for static site

- python/codepipeline-docker-build/Pipeline.py
> fix: correct minor typos in code

- java/hello-world/pom.xml
- java/hello-world/src/main/java/software/amazon/awscdk/examples/HelloJavaStack.java
- java/hello-world/src/test/java/software/amazon/awscdk/examples/SinkQueueTest.java
- java/lambda-cron/pom.xml
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
- java/lambda-cron/src/test/resources/software/amazon/awscdk/examples/testCronLambdaExpected.json
> chore: update Java examples

- csharp/my-widget-service/cdk.json
- csharp/my-widget-service/src/MyWidgetService/MyWidgetService.csproj
- csharp/my-widget-service/src/MyWidgetService/MyWidgetServiceStack.cs
- csharp/my-widget-service/src/MyWidgetService/Program.cs
- Added the dependency on the JSII Roslyn analyzers package.
- Removed now-unnecessary `null` arguments for "default props".
- Upgraded Lambda's runtime to Node-10.x (Node-8.x being deprecated)
---
> chore: clean up C# example

- python/appsync-graphql-dynamodb/requirements.txt
Description of changes:
Correct minor typos in appsync-graphql-dynamodb/requirements.txt
Change _ to - to make it consistent with other examples
---
> fix: correct minor typos in appsync-graphql-dynamodb/requirements.txt

- README.md
> fix: Added .NET link to README.

- CONTRIBUTING.md
- java/hello-world/src/main/java/software/amazon/awscdk/examples/HelloJavaApp.java
- java/hello-world/src/main/java/software/amazon/awscdk/examples/HelloJavaStack.java
- java/hello-world/src/main/java/software/amazon/awscdk/examples/SinkQueue.java
- java/hello-world/src/main/java/software/amazon/awscdk/examples/SinkQueueProps.java
- java/hello-world/src/test/java/software/amazon/awscdk/examples/SinkQueueTest.java
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronApp.java
- java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java
- java/lambda-cron/src/test/java/software/amazon/awscdk/examples/LambdaCronStackTest.java
- java/lambda-cron/src/test/java/software/amazon/awscdk/examples/TestUtils.java
- java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceApp.java
- java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceStack.java
- java/my-widget-service/src/test/java/software/amazon/awscdk/examples/MyWidgetServiceTest.java
- java/my-widget-service/src/test/java/software/amazon/awscdk/examples/TestUtils.java
- java/resource-overrides/src/main/java/software/amazon/awscdk/examples/ResourceOverridesApp.java
- java/resource-overrides/src/main/java/software/amazon/awscdk/examples/ResourceOverridesStack.java
- java/resource-overrides/src/test/java/software/amazon/awscdk/examples/ResourceOverridesStackTest.java
Formats existing java examples using google-java-format. Adds 'style and formatting' section to CONTRIBUTING.md regarding java code formatting.
All existing examples were tested with `mvn compile` and `cdk synth` after formatting.
Fixes #198
---
> feat: Format Java Code

- typescript/api-cors-lambda-crud-dynamodb/package.json
- typescript/application-load-balancer/package.json
- typescript/appsync-graphql-dynamodb/package.json
- typescript/classic-load-balancer/package.json
- typescript/custom-resource/package.json
- typescript/ecs/cluster/package.json
- typescript/ecs/cross-stack-load-balancer/package.json
- typescript/ecs/ecs-network-load-balanced-service/package.json
- typescript/ecs/ecs-service-with-advanced-alb-config/package.json
- typescript/ecs/ecs-service-with-logging/package.json
- typescript/ecs/ecs-service-with-task-networking/package.json
- typescript/ecs/ecs-service-with-task-placement/package.json
- typescript/ecs/fargate-application-load-balanced-service/package.json
- typescript/ecs/fargate-service-with-auto-scaling/package.json
- typescript/ecs/fargate-service-with-local-image/package.json
- typescript/ecs/fargate-service-with-logging/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-bg-pipeline/package.json
- typescript/elasticbeanstalk/elasticbeanstalk-environment/package.json
- typescript/my-widget-service/package.json
- typescript/resource-overrides/package.json
- typescript/static-site/package.json
- typescript/stepfunctions-job-poller/package.json
Updates all typescript dependencies to v3.7.2 in order to resolve issue described here: [cdk#5497](https://github.com/aws/aws-cdk/issues/5497)
Fixes #206  
---
> fix: update typescript to >3.7

- .travis.yml
- java/custom-resource/pom.xml
> fix: update travis to use jsii superchain

- typescript/ecs/fargate-service-with-local-image/index.ts
fixes #227 
Please read the [Contribution guidelines][1] and follow the pull-request
checklist.
[1]: https://github.com/aws-samples/aws-cdk-examples/blob/master/CONTRIBUTING.md
-->
Fixes # 
---
> fix: change ecs local example to ALB

- csharp/random-writer/src/RandomWriter/RandomWriter.csproj
Addressing feedback provided in #263
Rationale: so they can serve as canaries for changes that might be breaking in the future
---
> chore: unpin cdk versions 

- README.md
> docs: fix run java example instructions

- python/dynamodb-lambda/dynamodb_lambda/dynamodb_lambda_stack.py
> fix: Correct minor typos in dynamodb_lambda_stack.py

- python/docker-app-with-asg-alb/dockerized_app_cdk/rds_stack.py
- python/new-vpc-alb-asg-mysql/cdk_vpc_ec2/cdk_rds_stack.py
- python/rds/app.py
- scripts/build-java.sh
Upgrades to the latest API from the RDS package.
---
> fix(python/rds): upgrade to new API

- java/hello-world/src/test/java/software/amazon/awscdk/examples/SinkQueueTest.java
- java/hello-world/src/test/resources/software/amazon/awscdk/examples/testSubscribeTopics.expected.json
> chore: fix build by updating expectations

- java/resource-overrides/src/test/resources/software/amazon/awscdk/examples/testResourceOverrides.expected.json
> chore: fix Java tests failing due to changed SSM parameter imports

- python/new-vpc-alb-asg-mysql/README.md
Fix a few typos and correct some terminology.
> fix: minor README issues

- scripts/build-csharp.sh
- scripts/build-java.sh
- scripts/build-python.sh
- scripts/build-typescript.sh
- scripts/build.sh
- scripts/synth.sh
raise verbosity in builds to aid debugging on build failures.
---
> chore: verbose builds

- python/image-content-search/stack/cdk.py
- typescript/lambda-api-ci/jest.config.js
- typescript/lambda-api-ci/package.json
- typescript/lambda-cron/lambda-cron.test.ts
Last set of failures causing the build to break (I hope). 🤞
> chore: fix python and typescript build breaks

- .mergify.yml
- python/appsync-graphql-dynamodb/requirements.txt
- python/custom-resource/requirements.txt
- python/ec2/instance/requirements.txt
- python/emr/requirements.txt
- python/s3-object-lambda/app.py
- python/s3-object-lambda/requirements.txt
- python/s3-object-lambda/stacks/s3_object_lambda_stack.py
Fixes missing dependencies in some python examples and old imports in
python s3-object-lambda stack.
Fixes # 
---
> fix: broken python build

- python/api-eventbridge-lambda/README.md
Fix some typos:
- `srvices` --> `services`
- `Rules ,` --> `Rules,`
- `for every` --> `every`
As a non native English speaker I am not sure about the last one but as far as I know it's `for every second` and `every 60 seconds`?
Other than that great repo and docs 🙏
> docs: correct spelling of README

- python/dynamodb-lambda/setup.py
* Add a missing comma to `install_requires`.
> fix: Missing comma

- typescript/api-cors-lambda-crud-dynamodb/cdk.json
index.js value is not execute "cdk deploy" and getting 
> is not recognized as an internal or external command
Fixes # 
---
> fix(typescript): Update cdk.json in api-cors-lambda

- typescript/static-site/static-site.ts
This PR updates the static-sites example to use the new Distribution API following the migration instructions outlined here: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html#migrating-from-the-original-cloudfrontwebdistribution-to-the-newer-distribution-construct.
The changes replace the CloudFrontWebDistribution with Distribution and modifies the way that the certificate is associated with the Distribution.
Fixes https://github.com/aws-samples/aws-cdk-examples/issues/609
> feat(Typescript): Updated static-site example to use new Distribution API

- java/ecs/fargate-load-balanced-service/src/test/resources/com/amazonaws/cdk/examples/expected.cfn.json
This PR fixes a failing Java test in the main branch.
Fixes https://github.com/aws-samples/aws-cdk-examples/issues/723
SIM V694428904
---
> fix(java tests): failing Java test on main branch

- python/batch/batch-arm64-instance-type/app.py
- python/batch/batch-arm64-instance-type/requirements.txt
- python/batch/batch-using-fargate/app.py
- python/batch/batch-using-fargate/requirements.txt
- python/batch/batch-with-EC2/app.py
- python/batch/batch-with-EC2/requirements.txt
Updates batch-arm64-instance-type to use the new batch API.
Fixes #839
---
> update batch examples to use new batch API

- python/image-content-search/src/landingPage/index.html
> chore: update version of jquery

- .github/workflows/build-pull-request.yml
> Update build image to node18 from node14

- typescript/README.md
- typescript/aws-transfer-sftp-server/aws-transfer-sftp-server.ts
Update Table of Contents and add missing CfnOutput
Fixes https://github.com/aws-samples/aws-cdk-examples/issues/553
---
> fix: Update Table of Contents and add missing CfnOutput

- .github/workflows/build-pull-request.yml
Fixes # Bad PR that only got part of the changes.
---
> feat: test build only on changed code all commits

- .github/workflows/build-pull-request.yml
- scripts/build-csharp.sh
- scripts/build-go.sh
- scripts/build-java.sh
- scripts/build-python.sh
- scripts/build-typescript.sh
Reverts changes to the build system that is breaking on docker-in-docker
---
> Revert incremental build

- .github/workflows/handle-stale-discussions.yml
> (chore): added stale discussion bot

- typescript/amplify-console-app/README.md
> typo fix in typescript/amplify-console-app/README.md

- CONTRIBUTING.md
- README.md
Updating stance on Language Parity. 
---
> Fix:Language Parity Stance and Links

- java/resource-overrides/pom.xml
> Fix: guava security

- go/eks/cluster-graviton/cluster.go
- go/eks/cluster-graviton/cluster_test.go
- go/eks/cluster/cluster.go
- go/eks/cluster/cluster_test.go
- typescript/eks/cluster/index.ts
> feat(ts-go/eks): add sample code for creating Fargate profile

- typescript/appsync-graphql-typescript-resolver/.gitignore
- typescript/appsync-graphql-typescript-resolver/.npmignore
- typescript/appsync-graphql-typescript-resolver/README.md
- typescript/appsync-graphql-typescript-resolver/bin/appsync-graphql-typescript-resolver.ts
- typescript/appsync-graphql-typescript-resolver/cdk.json
- typescript/appsync-graphql-typescript-resolver/jest.config.js
- typescript/appsync-graphql-typescript-resolver/lib/appsync-graphql-typescript-resolver-stack.ts
- typescript/appsync-graphql-typescript-resolver/lib/schema.graphql
- typescript/appsync-graphql-typescript-resolver/package.json
- typescript/appsync-graphql-typescript-resolver/resolvers/.eslintrc.js
- typescript/appsync-graphql-typescript-resolver/resolvers/esbuild.config.mjs
- typescript/appsync-graphql-typescript-resolver/resolvers/jest.config.js
- typescript/appsync-graphql-typescript-resolver/resolvers/package.json
- typescript/appsync-graphql-typescript-resolver/resolvers/src/todo-resolver.test.ts
- typescript/appsync-graphql-typescript-resolver/resolvers/src/todo-resolver.ts
- typescript/appsync-graphql-typescript-resolver/resolvers/tsconfig.json
- typescript/appsync-graphql-typescript-resolver/tsconfig.json
> feat: add typescript appsync resolver example

- .github/actions/setup-language/action.yml
Update the runtimes for github actions.
> chore: update runtimes

- python/image-content-search/src/landingPage/index.html
- python/image-content-search/src/landingPage/main.py
> Fix(py/image-content-search: Swap replace with format

- .gitignore
> Add note about ignoring cdk.context.json

- typescript/postgres-lambda/README.md
> fix(postgres-lambda): readme

- python/image-content-search/src/landingPage/main.py
This small PR fixes the landing page handler that was changed in commit 911589408bf25adc9f0d457eff60523d4f9a4bb7.
> fix(py/image-content-searc): correct landing page handler
